#!/bin/bash
## \file    storage_report.sh
#  \author  Scott Wales <scott.wales@unimelb.edu.au>
#
#  Copyright 2015 ARC Centre of Excellence for Climate Systems Science
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -eu

ROOT=/g/data1/ua8

printf '%-30s     %-9s     %-9s\n' 'Project' 'Used (GB)' 'Old (GB)'
echo '-----------------------------------------------------------'

total_used='0'
total_old='0'
count=0

for dir in ${ROOT}/*; do
    proj=$(basename "${dir}")

    # Convert 'du' result to GB
    used=$(du -s "${dir}" | awk '{print $1/1024/1024}')

    # Get usage of files older than $AGE days
    AGE=90
    old=$(find "${dir}" -atime "+${AGE}" -printf '%k\n' | awk '{sum+=$1}END{print sum/1024/1024}')

    # Convert to a %
    pct_old=$(echo | awk '{print '"${old}"'/'"${used}"'*100}')

    printf '%-30s    %9.0f    %9.0f   (%3.0f%%)\n' "${proj}" "${used}" "${old}" "${pct_old}"

    # Add to sums
    total_used=$(echo "${used} ${total_used}" | awk '{print $1 + $2}')
    total_old=$(echo "${old} ${total_old}" | awk '{print $1 + $2}')
done

echo '-----------------------------------------------------------'
pct_old=$(echo | awk '{print '"${total_old}"'/'"${total_used}"'*100}')
printf '%-30s    %9.0f    %9.0f   (%3.0f%%)\n' "Total" "${total_used}" "${total_old}" "${pct_old}"
