#!/usr/bin/env python
"""
file:   /projects/access/admin/latest-pypi-version.py
author: Scott Wales (scott.wales@unimelb.edu.au)

Print the latest version of a package on pypi

Copyright 2013 ARC Centre of Excellence for Climate System Science

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""
Use PyPI's API to find the latest version of the given library
"""

import xmlrpclib
import sys

client = xmlrpclib.ServerProxy('http://pypi.python.org/pypi')
releases = client.package_releases(sys.argv[1])
if len(releases) > 0:
    print releases[0]
else:
    exit(-1)
